In [1]:
import pandas as pd
from random import randint
from sklearn.ensemble import GradientBoostingClassifier as GBC
from sklearn.cross_validation import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
import pickle
from sklearn.metrics import confusion_matrix
from numpy import array as array

C:\Users\birdmw\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df = pd.read_csv("data/raw_games.csv")

In [3]:
df

Unnamed: 0   0  1   2   3   4  5  6   7   8   9  10  11  12  13  \
0               0  21  0   0   0   0  0  1  21   1   0   1   2   1   0   
1               1   8  4   0   0   1  0  1  24   5   4   0   0   1   0   
2               2   1  5   5   5   4  0  5   1   5   5   4   4   4   0   
3               3   4  2   1   6   3  6  0   5   2   4   1   9   2   3   
4               4  18  2   2   0   3  2  1  13   0   0   0   7   0   0   
5               5  16  0   0   0   0  0  1   7   5   1  10   0   0   8   
6               6   6  6   1   2   3  0  1   5   8   0   4   1  10   1   
7               7  21  4   2   0   0  0  0  18   1   1   1   0   0   0   
8               8   5  7   1   0   8  8  4   3   2   1   7   0   2   0   
9               9  10  0   2   2   0  4  0  15   0   1   3   6   5   0   
10             10  29  0   0   0   0  0  0  14   1   1   1   0   0   2   
11             11  16  1   2   3   4  1  1  10   1   1   5   3   0   0   
12             12  29  2   0   1   0  0  2  12   0   1   1   0   0   0   
13             13   5  0   3   3   3  2  6  10   4  11   0   0   0   1   
14             14   0  4   4   0   0  6  6   2   5   5   4   4   4   4   
15             15  14  0   1  14   0  1  0  16   0   0   2   0   0   0   
16             16  16  0   0   0   0  0  1  23   0   4   2   1   0   1   
17             17  12  0   0   0   1  1  7  13   1   0   1   3   0   9   
18             18   9  0   0   0   0  3  3  13   3   0  14   2   0   1   
19             19  16  4   1   1   6  0  0  15   2   0   0   0   2   1   
20             20   9  2   1   1   0  2  1  19   0   4   1   2   3   3   
21             21  11  8   0   5   0  1  5   8   2   3   0   2   0   3   
22             22   8  9   0  10   4  1  2   3   0   3   2   1   4   1   
23             23  17  0   0   0   0  1  7  15   0   1   0   5   0   2   
24             24  14  0   0   2   2  0  0  18   0   7   3   1   0   1   
25             25   3  1   7   3   7  0  1  12   0   0   8   0   6   0   
26             26   2  0   2   7   7  6  0   7   0   0   3   0   7   7   
27             27   8  1   8   0   9  0  7   5   0   0   2   0   1   7   
28             28   7  0   3   7   7  7  0   1   0   6   2   7   1   0   
29             29   5  8   2   0   7  0  0   4   0   7   3   2   0  10   
...           ...  .. ..  ..  ..  .. .. ..  ..  ..  ..  ..  ..  ..  ..   
99970       99970  16  2   0   4   1  0  0  18   0   2   0   3   1   1   
99971       99971   6  2   2   0   1  0  3  10   2   0   2  13   5   2   
99972       99972   7  1   1   0   2  0  0  27   1   0   1   1   2   5   
99973       99973  25  0   2   0   0  2  1  18   0   0   0   0   0   0   
99974       99974  25  0   0   0   0  0  0  23   0   0   0   0   0   0   
99975       99975  20  1   0   0   0  0  1  23   1   0   0   0   2   0   
99976       99976  23  2   0   0   0  0  3  15   0   0   0   3   1   1   
99977       99977   5  0  11   1   4  0  2  12   0  10   0   1   0   2   
99978       99978  25  0   0   0   0  0  0  23   0   0   0   0   0   0   
99979       99979  12  0   0   1   2  1  1  11  14   0   1   1   0   4   
99980       99980  16  1   1   0   6  0  0   7   0   0   0   7   0  10   
99981       99981  22  0   0   0   0  1  0  22   0   1   2   0   0   0   
99982       99982   9  0   1   2  11  3  1   9   1   3   0   0   1   7   
99983       99983   2  6   5   5   0  0  1   3   7   6   0   7   5   1   
99984       99984  16  0   0   0   1  1  0  17   0   3   2   6   1   1   
99985       99985   6  3   1  11   2  3  1   7   6   3   0   0   1   4   
99986       99986  11  0   2   4   9  0  2   6  11   0   0   2   1   0   
99987       99987   3  3   0   2   8  8  2   3   7   6   0   5   1   0   
99988       99988   9  2   8   0   0  0  8   4   0   9   0   6   0   2   
99989       99989   5  0   5   5   0  1  0  18   0   0   7   0   6   1   
99990       99990  18  1   1   0   0  0  0  22   0   0   0   1   3   2   
99991       99991   6  2   1   1   6  0  5   7  10   0   4   1   2   3   
99992      

In [4]:
def winner(name):
    if name == "player_1":
        return 0
    elif name == "player_2":
        return 2
    else: # tie
        return 1

In [5]:
df.columns

Index([u'Unnamed: 0', u'0', u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8',
       u'9', u'10', u'11', u'12', u'13', u'turn', u'winner'],
      dtype='object')

In [6]:
X = df[[str(x) for x in [0,1,2,3,4,5,6,7,8,9,10,11,12,13]]]
y = df['winner'].apply(lambda x: winner(x))

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [8]:
model = GBC(n_estimators=500, verbose=1).fit(X_train, y_train)

      Iter       Train Loss   Remaining Time 
         1       86726.9550            1.52m
         2       83555.1944            1.56m
         3       80880.7789            1.58m
         4       78655.7360            1.59m
         5       76720.0828            1.60m
         6       75104.9743            1.60m
         7       73708.0397            1.62m
         8       72533.1532            1.63m
         9       71502.9981            1.64m
        10       70626.1007            1.65m
        20       65971.5397            1.66m
        30       64333.2562            1.63m
        40       63606.9015            1.60m
        50       63132.2735            1.57m
        60       62830.0978            1.53m
        70       62582.1394            1.48m
        80       62392.6780            1.44m
        90       62236.6580            1.40m
       100       62113.3316            1.36m
       200       61299.7124            1.00m
       300       60702.4743           39.99s
       40

In [9]:
y_predicted = model.predict(X_test)

In [10]:
rms = sqrt(mean_squared_error(y_test, y_predicted))

In [11]:
print rms

1.0764292824


In [ ]:
array([[3734,    2, 1104],
       [ 337,   49,  256],
       [1297,    4, 3217]])

In [14]:
confusion_matrix(y_test, y_predicted)

array([[3528,    4, 1282],
       [ 314,   30,  288],
       [1463,    1, 3090]])

In [15]:
with open("data/GBC_model_500.pkl", 'wb') as f:
    pickle.dump(model, f)

In [16]:
model.predict_proba(X_test)

array([[ 0.40939546,  0.04344761,  0.54715693],
       [ 0.44818697,  0.17780128,  0.37401175],
       [ 0.58291856,  0.07016746,  0.34691397],
       ..., 
       [ 0.4917312 ,  0.05074078,  0.45752801],
       [ 0.76172891,  0.06045123,  0.17781986],
       [ 0.35414861,  0.06417119,  0.58168019]])

In [17]:
X_test

0   1   2   3  4   5   6   7   8   9  10  11  12  13
71317   5   3   8   0  6   6   1   2   6   1   7   0   1   2
97155  22   0   2   0  0   0   1  22   0   0   1   0   0   0
10349  11   0  12   2  4   0   0  13   0   0   4   0   2   0
81264  23   0   0   0  0   2   0  22   0   0   0   1   0   0
85801  20   1   0   1  0   1   1  20   0   0   2   0   1   1
26257   3   0   1   2  2   0   3   7   2   9   6   0   4   9
40855  10   6   0  10  8   0   7   2   0   2   1   2   0   0
18926   8   1   0   6  2   2   1   7   1   1  11   0   8   0
51711  26   0   1   0  0   1   1   9   0   5   2   2   0   1
79153  19   1   1   1  6   2   0   7   3   0   2   2   3   1
95681   0   4   4   4  4   0   5   1   0   6   5   5   5   5
77201   8   4   0   9  2   5   1   6   1   2   1   0   0   9
74191   7   8   0   0  9   0  10   6   0   0   2   0   3   3
49732  12   0   5   0  2   4   0  20   0   1   0   2   2   0
82635   5   1   8   2  0   0   0  15   0   0   0   8   1   8
17672  24   0   1   0  0   0   0  16   1   2   3   0   1   0
31467   6  10   0   4  1  10   0   9   1   1   2   3   0   1
10725  10   0   1   7  9   4   1   8   2   1   0   0   2   3
33500  16   1   0   0  3   4   0  15   1   0   0   2   6   0
75081   3   7   2   0  1   7   0   4   8   0   6   1   0   9
24329  24   0   0   0  0   0   0  23   0   0   0   0   1   0
86073  28   0   0   0  1   0   1  17   0   0   0   1   0   0
24023   5   0   0   2  3   0  10  11   1   8   0   1   2   5
71790   8   0   7   1  3   2   0  11   1   0   6   2   2   5
26653   7   0   6   3  8   0   3   4   1   3   4   9   0   0
1096   16   2   1   4  0   0   2  16   2   0   1   2   2   0
26192   5   0   0   2  0   0   0  24   2   3   3   8   0   1
39627  15   1   1   0  2   1   2  15   1   2   5   0   2   1
44520   8   0   0   0  4   3   0  16  11   0   6   0   0   0
27969  19   2   4   4  1   0   4   8   1   1   0   2   0   2
...    ..  ..  ..  .. ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
32925   7   5   5   2  1   5   1   8   5   2   4   0   1   2
31324   5   0   3  12  5   3   3   7   3   3   0   0   0   4
68949  15   1   2   0  1   0   2  18   1   3   0   3   1   1
38133  19   1   1   0  2   5   8  10   0   0   0   1   1   0
1837   10   0   2   1  1   6   3   8   0   7   2   3   0   5
70601  20   1   2   0  0   1   1  20   0   0   0   2   0   1
75277  10   1   2   1  0   6   1  17   1   1   2   0   2   4
76607  11   0   0   9  0   1   1  19   0   0   2   4   0   1
26934  17   1   0   1  5   2   5  15   0   0   0   2   0   0
99779  11   0   6   2  6   1   1   5   4   2   6   1   3   0
5426    8   7   0   4  0   2   0   8   2  12   1   0   3   1
28757   0   4   4   0  5   0   6   2   5   5   5   4   4   4
98705  32   0   0   0  0   1   0  12   0   0   0   2   0   1
16343   1   5   5   5  0   5   5   1   5   4   4   4   4   0
11583   4   6   6   6  5   1   1   2   6   1   2   1   7   0
19261  20   2   0   0  0   1   3  21   0   0   1   0   0   0
39365   6   2   1   6  1   0   5  14   3   1   2   3   3   1
61848  16   4   0   4  2   1   1  11   0   1   3   3   2   0
78464   7   2   0   7  1   0  10   3   0   0   2   2  11   3
32811  13   1   1   1  5   1   0  19   0   0   1   3   1   2
38811   1   5   0   1  6   2   0   3   0   8   6   2   7   7
49872  17   1   1   0  0   7   2  18   0   0   0   0   2   0
73996  13   0   2   1  7   0   0   6   8   7   1   2   1   0
73012   4   1   9   1  2   2   8  17   1   0   0   1   1   1
90451  12   1   0   0  0   2   6  26   0   1   0   0   0   0
18583  22   0   0   0  2   0   0  20   0   1   3   0   0   0
47522   2   1   6   1  6   6   5   1   1   0   6   0   7   6
32723   2   2   1   7  6   6   5   1   5   4   4   4   0   1
87928   3   1   0   3  0   3   1  13   7   1   3   2   9   2
58856  18   0   5   0  4   2   0  12   0   0   0   2   3   2

[10000 rows x 14 columns]

In [18]:
X_test.columns

Index([u'0', u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10',
       u'11', u'12', u'13'],
      dtype='object')

In [25]:
a = [randint(0,10) for i in range(14)]
print a
model.predict_proba(array(a).reshape(1,-1))

[7, 2, 3, 8, 9, 0, 4, 4, 4, 2, 0, 5, 4, 5]


array([[ 0.40727408,  0.05371044,  0.53901548]])